apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    druidOpResourceHash: eDET+3jGV3LHfxRFYPMyOXhHjUw=
  creationTimestamp: "2023-10-31T04:54:17Z"
  generation: 1
  labels:
    app: druid
    component: broker
    druid_cr: tiny-cluster
    environment: stage
    nodeSpecUniqueStr: druid-tiny-cluster-brokers
    release: alpha
  name: druid-tiny-cluster-brokers
  namespace: druid
  ownerReferences:
  - apiVersion: druid.apache.org/v1alpha1
    controller: true
    kind: Druid
    name: tiny-cluster
    uid: fa4ddd44-00f6-433b-8878-5eb06e6d5502
  resourceVersion: "318138"
  uid: 64b2a592-0b13-4f60-a211-a23aaba3cbae
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: druid
      component: broker
      druid_cr: tiny-cluster
      environment: stage
      nodeSpecUniqueStr: druid-tiny-cluster-brokers
      release: alpha
  serviceName: druid-tiny-cluster-brokers
  template:
    metadata:
      annotations:
        dummykey: dummyval
      creationTimestamp: null
      labels:
        app: druid
        component: broker
        druid_cr: tiny-cluster
        environment: stage
        nodeSpecUniqueStr: druid-tiny-cluster-brokers
        release: alpha
    spec:
      affinity: {}
      containers:
      - command:
        - /druid.sh
        - broker
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: configMapSHA
          value: QrbjBrvhT2s0AnA+LyLC8a7WLMY=-4opMJHBw2g4iUU4ZPq1zO2Uz2po=
        image: apache/druid:25.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /status/health
            port: 8088
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: druid-tiny-cluster-brokers
        ports:
        - containerPort: 8088
          name: druid-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /status/health
            port: 8088
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          privileged: true
        startupProbe:
          failureThreshold: 20
          httpGet:
            path: /druid/broker/v1/readiness
            port: 8088
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/druid/conf/druid/cluster/_common
          name: common-config-volume
          readOnly: true
        - mountPath: /opt/druid/conf/druid/cluster/query/broker
          name: nodetype-config-volume
          readOnly: true
        - mountPath: /opt/druid/extensions/mysql-connector
          name: mysqlconnector
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - wget -O /tmp/mysql-connector-j-8.0.32.tar.gz https://downloads.mysql.com/archives/get/p/3/file/mysql-connector-j-8.0.32.tar.gz
          && cd /tmp && tar -xf /tmp/mysql-connector-j-8.0.32.tar.gz && cp /tmp/mysql-connector-j-8.0.32/mysql-connector-j-8.0.32.jar
          /opt/druid/extensions/mysql-connector/mysql-connector-java.jar
        image: apache/druid:25.0.0
        imagePullPolicy: IfNotPresent
        name: mysqlconnector
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/druid/extensions/mysql-connector
          name: mysqlconnector
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: tiny-cluster-druid-common-config
        name: common-config-volume
      - configMap:
          defaultMode: 420
          name: druid-tiny-cluster-brokers-config
        name: nodetype-config-volume
      - emptyDir: {}
        name: mysqlconnector
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: data-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: standard
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: druid-tiny-cluster-brokers-795c769cdd
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: druid-tiny-cluster-brokers-795c769cdd
  updatedReplicas: 1
