apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap1
data:
  database-url: "mysql://mydbserver:3306/mydatabase"
  api-key: "your-api-key-here"

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: dXNlcm5hbWU=  # Base64-encoded username
  password: cGFzc3dvcmQ=  # Base64-encoded password

