apiVersion: v1
data:
  jvm.config: |
    -server
    -XX:MaxDirectMemorySize=10240g
    -Duser.timezone=UTC
    -Dfile.encoding=UTF-8
    -Dlog4j.debug
    -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
  log4j2.xml: |-
    <?xml version="1.0" encoding="UTF-8" ?>
    <Configuration status="TRACE">
        <Appenders>
            <Http name="Http" url="https://demo.parseable.io/api/v1/ingest" method="POST">
              <Property name="Authorization" value="Basic YWRtaW46YWRtaW4=" />
              <Property name="X-P-Stream" value="druide2e" />
              <Property name="Accept" value="application/json" />
              <Property name="X-Java-Runtime" value="$${java:runtime}" />
              <JsonLayout properties="true"/>
            </Http>
        </Appenders>
        <Loggers>
            <Root level="info">
                <AppenderRef ref="Http"/>
            </Root>
        </Loggers>
    </Configuration>
  runtime.properties: |
    druid.port=8088
    druid.service=druid/router
    # HTTP proxy
    druid.router.http.numConnections=50
    druid.router.http.readTimeout=PT5M
    druid.router.http.numMaxThreads=100
    druid.server.http.numThreads=100
    # Service discovery
    druid.router.defaultBrokerServiceName=druid/broker
    druid.router.coordinatorServiceName=druid/coordinator
    # Management proxy to coordinator / overlord: required for unified web console.
    druid.router.managementProxy.enabled=true
kind: ConfigMap
metadata:
  labels:
    app: druid
    component: router
    druid_cr: tiny-cluster
    environment: stage
    nodeSpecUniqueStr: druid-tiny-cluster-routers
    release: alpha
  name: druid-tiny-cluster-routers-config
  namespace: druid
