apiVersion: v1
data:
  jvm.config: |
    -server
    -Duser.timezone=UTC
    -Dfile.encoding=UTF-8
  common.runtime.properties: |
    #
    # Trying Druid Cluster with Zookeeper 
    #
    druid.zk.service.host=zookeeper-client.default.svc.cluster.local
    druid.zk.paths.base=/druid
    druid.zk.service.compress=false
    # Metadata Store
    druid.metadata.storage.type=derby
    druid.metadata.storage.connector.connectURI=jdbc:derby://localhost:1527/var/druid/metadata.db;create=true
    druid.metadata.storage.connector.host=localhost
    druid.metadata.storage.connector.port=1527
    druid.metadata.storage.connector.createTables=true
    # Deep Storage
    druid.storage.type=s3
    druid.storage.bucket=druid
    druid.storage.baseKey=druid/segments
    druid.s3.accessKey=minio
    druid.s3.secretKey=minio123
    druid.s3.protocol=http
    druid.s3.endpoint.signingRegion=us-east-1
    druid.s3.enablePathStyleAccess=true
    druid.s3.endpoint.url=http://myminio-hl.druid.svc.cluster.local:9000/
    #
    # Extensions
    #
    druid.extensions.loadList=["druid-avro-extensions", "druid-s3-extensions", "druid-hdfs-storage", "druid-kafka-indexing-service", "druid-datasketches"]
    #
    # Service discovery
    #
    druid.selectors.indexing.serviceName=druid/overlord
    druid.selectors.coordinator.serviceName=druid/coordinator
    druid.indexer.logs.type=s3
    druid.indexer.logs.s3Bucket=druid
    druid.indexer.logs.s3Prefix=druid/indexing-logs
    druid.lookup.enableLookupSyncOnStartup=false
  coordinators.properties: |
    druid.port=8088
    druid.service=druid/coordinator
    # HTTP server threads
    druid.coordinator.startDelay=PT30S
    druid.coordinator.period=PT30S
    # Configure this coordinator to also run as Overlord
    druid.coordinator.asOverlord.enabled=true
    druid.coordinator.asOverlord.overlordService=druid/overlord
    #druid.indexer.queue.startDelay=PT30S
    druid.indexer.storage.type=metadata
  brokers.properties: |
    druid.port=8088
    druid.service=druid/broker
    # HTTP server threads
    druid.broker.http.numConnections=5
    druid.server.http.numThreads=40
    # Processing threads and buffers
    druid.processing.buffer.sizeBytes=25000000
    #druid.sql.enable=true
  historicals.properties: |
    druid.port=8088
    druid.service=druid/historical
    #druid.processing.buffer.sizeBytes=25000000
    #druid.processing.numThreads=2
    # Segment storage
    druid.segmentCache.locations=[{"path":"/druid/data/segments","maxSize":10737418240}]
    druid.server.maxSize=10737418240
  middleManagers.properties: |
    druid.port=8088
    druid.service=druid/middleManager
    druid.worker.capacity=1
    druid.indexer.runner.javaOpts=-server -Xms128m -Xmx128m -XX:MaxDirectMemorySize=256m -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/druid/data/tmp -XX:+ExitOnOutOfMemoryError -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
    druid.indexer.task.baseTaskDir=/druid/data/baseTaskDir
    druid.server.http.numThreads=1
    druid.indexer.fork.property.druid.processing.buffer.sizeBytes=25000000
    druid.indexer.fork.property.druid.processing.numMergeBuffers=2
    druid.indexer.fork.property.druid.processing.numThreads=1
  overlords.properties: |
    druid.port=8088
    druid.service=druid/overlord
  routers.properties: |
    druid.port=8088
    druid.service=druid/router
    # HTTP proxy
    druid.router.http.numConnections=50
    druid.router.http.readTimeout=PT5M
    druid.router.http.numMaxThreads=100
    druid.server.http.numThreads=100
    # Service discovery
    druid.router.defaultBrokerServiceName=druid/broker
    druid.router.coordinatorServiceName=druid/coordinator
    # Management proxy to coordinator / overlord: required for unified web console.
    druid.router.managementProxy.enabled=true
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/created-by: druid
    app.kubernetes.io/instance: druid-sample
    app.kubernetes.io/managed-by: kubedb.com
    app.kubernetes.io/name: druids.kubedb.com
    app.kubernetes.io/part-of: druid
  name: druid-sample-config
  namespace: druid
type: Opaque
