apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: druid
    component: middleManager
    druid_cr: tiny-cluster
    environment: stage
    nodeSpecUniqueStr: druid-tiny-cluster-middlemanagers
    release: alpha
  name: druid-tiny-cluster-middlemanagers
  namespace: druid
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: druid
      component: middleManager
      druid_cr: tiny-cluster
      environment: stage
      nodeSpecUniqueStr: druid-tiny-cluster-middlemanagers
      release: alpha
  serviceName: druid-tiny-cluster-middlemanagers
  template:
    metadata:
      annotations:
        dummy: k8s_extn_needs_atleast_one_annotation
      labels:
        app: druid
        component: middleManager
        druid_cr: tiny-cluster
        environment: stage
        nodeSpecUniqueStr: druid-tiny-cluster-middlemanagers
        release: alpha
    spec:
      affinity: {}
      containers:
        - command:
            - /druid.sh
            - middleManager
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: apache/druid:25.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /status/health
              port: 8088
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: druid-tiny-cluster-middlemanagers
          ports:
            - containerPort: 8088
              name: druid-port
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /status/health
              port: 8088
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext:
            privileged: true
          startupProbe:
            failureThreshold: 10
            httpGet:
              path: /status/health
              port: 8088
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/druid/conf/druid/cluster/_common
              name: common-config-volume
              readOnly: true
            - mountPath: /opt/druid/conf/druid/cluster/data/middleManager
              name: nodetype-config-volume
              readOnly: true
            - mountPath: /opt/druid/extensions/mysql-connector
              name: mysqlconnector
            - mountPath: /druid/data/baseTaskDir
              name: data-volume
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - sh
            - -c
            - wget -O /tmp/mysql-connector-j-8.0.32.tar.gz https://downloads.mysql.com/archives/get/p/3/file/mysql-connector-j-8.0.32.tar.gz
              && cd /tmp && tar -xf /tmp/mysql-connector-j-8.0.32.tar.gz && cp /tmp/mysql-connector-j-8.0.32/mysql-connector-j-8.0.32.jar
              /opt/druid/extensions/mysql-connector/mysql-connector-java.jar
          image: apache/druid:25.0.0
          imagePullPolicy: IfNotPresent
          name: mysqlconnector
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/druid/extensions/mysql-connector
              name: mysqlconnector
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: tiny-cluster-druid-config
          name: common-config-volume
        - configMap:
            defaultMode: 420
            name: tiny-cluster-druid-config
            items:
              - key: middleManagers.properties
                path: runtime.properties
              - key: jvm.config
                path: jvm.config
          name: nodetype-config-volume
        - emptyDir: { }
          name: mysqlconnector
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: standard
        volumeMode: Filesystem
