apiVersion: v1
kind: Service
metadata:
  labels:
    app: druid
    component: middleManager
    druid_cr: tiny-cluster
    environment: stage
    nodeSpecUniqueStr: druid-tiny-cluster-middlemanagers
    release: alpha
  name: druid-tiny-cluster-middlemanagers
  namespace: druid
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: service-port
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: druid
    component: middleManager
    druid_cr: tiny-cluster
    environment: stage
    nodeSpecUniqueStr: druid-tiny-cluster-middlemanagers
    release: alpha
  sessionAffinity: None
  type: ClusterIP
