apiVersion: v1
kind: Service
metadata:
  labels:
    app: druid
    component: coordinator
    druid_cr: tiny-cluster-1
    environment: stage
    nodeSpecUniqueStr: druid-tiny-cluster-1-coordinators
    release: alpha
  name: druid-tiny-cluster-1-coordinators
  namespace: druid
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: service-port
      port: 8088
      protocol: TCP
      targetPort: 8088
  selector:
    app: druid
    component: coordinator
    druid_cr: tiny-cluster-1
    environment: stage
    nodeSpecUniqueStr: druid-tiny-cluster-1-coordinators
    release: alpha
  sessionAffinity: None
  type: ClusterIP
